/*
====================================================
FILE: 03_joins_business_queries.sql
PROJECT: SQL Northwind Analysis
AUTHOR: Ramses Omar López Soto

PURPOSE:
Apply JOIN operations to answer business-oriented
questions involving employees, suppliers, and markets.
====================================================
*/

-- Query 1: Analyze workload distribution across employees
-- Business question: How many orders has each employee handled?
-- LEFT JOIN ensures employees without orders are included
SELECT
    e.first_name || ' ' || e.last_name AS employee_name,
    COUNT(o.order_id) AS total_orders
FROM employees e
LEFT JOIN orders o
    ON e.employee_id = o.employee_id
GROUP BY employee_name
ORDER BY total_orders DESC;


-- Query 2: Calculate total revenue generated by each supplier
-- Business question: Which suppliers contribute the most to company revenue?
SELECT
    s.company_name AS supplier,
    SUM(od.unit_price * od.quantity * (1 - od.discount)) AS total_revenue
FROM suppliers s
JOIN products p
    ON s.supplier_id = p.supplier_id
JOIN order_details od
    ON p.product_id = od.product_id
GROUP BY s.company_name
ORDER BY total_revenue DESC;


-- Query 3: Analyze sales performance by country
-- Business question: Which geographic markets generate the highest revenue?
SELECT
    c.country,
    SUM(od.unit_price * od.quantity * (1 - od.discount)) AS total_sales
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_details od
    ON o.order_id = od.order_id
GROUP BY c.country
ORDER BY total_sales DESC;

-- Query 4: Identify employees with no orders
-- Business question: Which employees have not processed any orders?
SELECT
    e.first_name || ' ' || e.last_name AS employee_name
FROM employees e
LEFT JOIN orders o
    ON e.employee_id = o.employee_id
WHERE o.order_id IS NULL    
ORDER BY employee_name;
-- Query 5: List suppliers and the number of products they supply
-- Business question: Which suppliers provide the most products to the company?
SELECT
    s.company_name AS supplier,
    COUNT(p.product_id) AS total_products
FROM suppliers s
LEFT JOIN products p
    ON s.supplier_id = p.supplier_id
GROUP BY s.company_name
ORDER BY total_products DESC;
-- Query 6: Determine average order value by customer country
-- Business question: Which countries have the highest average order values?
SELECT
    c.country,
    AVG(od.unit_price * od.quantity * (1 - od.discount)) AS average_order_value 
FROM customers c
JOIN orders o   
    ON c.customer_id = o.customer_id
JOIN order_details od
    ON o.order_id = od.order_id
GROUP BY c.country
ORDER BY average_order_value DESC;
-- Query 7: Find the top 5 employees by total sales amount
-- Business question: Which employees generate the highest sales revenue?
SELECT
    e.first_name || ' ' || e.last_name AS employee_name,
    SUM(od.unit_price * od.quantity * (1 - od.discount)) AS total_sales
FROM employees e
JOIN orders o
    ON e.employee_id = o.employee_id
JOIN order_details od
    ON o.order_id = od.order_id
GROUP BY employee_name
ORDER BY total_sales DESC
LIMIT 5;
